# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c97aa17f774b77de83d93b5f4d79fb1a15d4eb73a50ece8bc3634688ec93aaeb63a4c389dd6a89cab6cdd729c573f00b3d8e4c5fae5182f998dc620d6c10b3

test:
  secret_key_base: 5b07e38e714f11c580c951b266997832ad2850b3b851e83a8a7dac20bee90138fef2970b4b49b3ad2c9ce5e10f6de151e2bc338121746d9dfe7d2d5a991bab74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
